name: Laravel

on:
  push:
    branches: [ "gh-action" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.3'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit


  build-and-push:
      name: Build & push
      runs-on: ubuntu-latest
      env:
          GOOGLE_APPLICATION_CREDENTIALS: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}'
          ARTIFACT_REGISTRY: asia-southeast2-docker.pkg.dev
          PROJECT: cukzlearn03
          APP: '${{ github.event.repository.name }}'

      steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}'

      - name: Get version
        run: echo "GITHUB_SHA_SHORT=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV
      
      - name: Upload to Artifact Registry
        run: |
          gcloud config set account cicd-dev@cukzlearn03.iam.gserviceaccount.com
          gcloud auth activate-service-account cicd-dev@cukzlearn03.iam.gserviceaccount.com --key-file=$GOOGLE_APPLICATION_CREDENTIALS --project=cukzlearn03
          gcloud auth configure-docker $ARTIFACT_REGISTRY
          docker build -t $ARTIFACT_REGISTRY/$PROJECT/test-laravel/$APP:${env.GITHUB_SHA_SHORT} .
          docker image push $ARTIFACT_REGISTRY/$PROJECT/test-laravel/$APP
